# Form implementation generated from reading ui file 'taskbox.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(405, 150)
        Form.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.outerFrame = QtWidgets.QFrame(parent=Form)
        self.outerFrame.setStyleSheet("QFrame#outerFrame {border: 1px solid rgb(200, 200, 200);}")
        self.outerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.outerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.outerFrame.setLineWidth(3)
        self.outerFrame.setObjectName("outerFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.outerFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.timeLabel = QtWidgets.QLabel(parent=self.outerFrame)
        self.timeLabel.setLineWidth(0)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout_2.addWidget(self.timeLabel, 1, 0, 1, 1)
        self.dateLabel = QtWidgets.QLabel(parent=self.outerFrame)
        self.dateLabel.setLineWidth(0)
        self.dateLabel.setObjectName("dateLabel")
        self.gridLayout_2.addWidget(self.dateLabel, 2, 0, 1, 1)
        self.taskTextBrowser = QtWidgets.QTextBrowser(parent=self.outerFrame)
        self.taskTextBrowser.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.taskTextBrowser.setLineWidth(0)
        self.taskTextBrowser.setObjectName("taskTextBrowser")
        self.gridLayout_2.addWidget(self.taskTextBrowser, 0, 1, 3, 1)
        self.innerFrame = QtWidgets.QFrame(parent=self.outerFrame)
        self.innerFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.innerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.innerFrame.setObjectName("innerFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.innerFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(7, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.doneCheckBox = QtWidgets.QCheckBox(parent=self.innerFrame)
        self.doneCheckBox.setText("")
        self.doneCheckBox.setObjectName("doneCheckBox")
        self.gridLayout_3.addWidget(self.doneCheckBox, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(7, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.innerFrame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.outerFrame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.timeLabel.setText(_translate("Form", "TextLabel"))
        self.dateLabel.setText(_translate("Form", "TextLabel"))
