# Form implementation generated from reading ui file 'tbox3.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 125)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(16777215, 125))
        Form.setStyleSheet("font: 11pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.startLabel = QtWidgets.QLabel(parent=Form)
        self.startLabel.setStyleSheet("color: rgb(80, 80, 80);\n"
"")
        self.startLabel.setObjectName("startLabel")
        self.gridLayout.addWidget(self.startLabel, 1, 0, 3, 2)
        self.endLabel = QtWidgets.QLabel(parent=Form)
        self.endLabel.setStyleSheet("color: rgb(80, 80, 80);")
        self.endLabel.setObjectName("endLabel")
        self.gridLayout.addWidget(self.endLabel, 4, 0, 1, 2)
        self.innerFrame = QtWidgets.QFrame(parent=Form)
        self.innerFrame.setStyleSheet("")
        self.innerFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.innerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.innerFrame.setObjectName("innerFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.innerFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(7, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(7, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 2, 1, 1)
        self.doneCheckBox = QtWidgets.QCheckBox(parent=self.innerFrame)
        self.doneCheckBox.setStyleSheet("")
        self.doneCheckBox.setText("")
        self.doneCheckBox.setObjectName("doneCheckBox")
        self.gridLayout_3.addWidget(self.doneCheckBox, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.innerFrame, 0, 0, 1, 1)
        self.taskEdit = QtWidgets.QTextEdit(parent=Form)
        self.taskEdit.setObjectName("taskEdit")
        self.gridLayout.addWidget(self.taskEdit, 0, 2, 6, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.startLabel.setText(_translate("Form", "TextLabel"))
        self.endLabel.setText(_translate("Form", "TextLabel"))
